<?php


namespace iikoExchangeBundle;


use Symfony\Component\HttpKernel\Bundle\Bundle;

class iikoExchangeBundle extends Bundle
{
	const BUNDLE_CODE = 'exchange';

	public function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub
	}
}