<?php


namespace App;


use Symfony\Component\HttpKernel\Bundle\Bundle;

class iikoExchangeBundle extends Bundle
{
	public function boot()
	{
		parent::boot(); // TODO: Change the autogenerated stub
	}
}